.8086
.MODEL medium
INCLUDE gb_defs.inc

; CB prefix instruction handling

EXTRN CORE1_START

CORE1 SEGMENT
  ASSUME CS:CORE1
ENDS



SEGMENT CORE2  USE16 PARA PUBLIC 'CODE'
ASSUME  CS:CORE2

OPCODE_DEFINE 000h   ; RLC B
xchg  ax, bp
rol   ah, 1
xchg  ax, bp
CORE2_START:
public CORE2_START
LOAD_NEXT_INSTRUCTION_SEGMENT_2 2

pointer_to_core_1:
public pointer_to_core_1
dw CORE1_START, SEG CORE1





OPCODE_DEFINE 001h   ; RLC C
xchg  ax, bp
rol   al, 1
xchg  ax, bp
LOAD_NEXT_INSTRUCTION_SEGMENT_2 2

OPCODE_DEFINE 002h   ; RLC D
rol   dh, 1
LOAD_NEXT_INSTRUCTION_SEGMENT_2 2

OPCODE_DEFINE 003h   ; RLC E
rol   dl, 1
LOAD_NEXT_INSTRUCTION_SEGMENT_2 2

OPCODE_DEFINE 004h   ; RLC H
rol   bh, 1
LOAD_NEXT_INSTRUCTION_SEGMENT_2 2

OPCODE_DEFINE 005h   ; RLC L
rol   bl, 1
LOAD_NEXT_INSTRUCTION_SEGMENT_2 2

OPCODE_DEFINE 006h   ; RLC (HL)
rol   byte ptr ds:[bx], 1
LOAD_NEXT_INSTRUCTION_SEGMENT_2 4

OPCODE_DEFINE 007h   ; RLC A
rol   cl, 1
LOAD_NEXT_INSTRUCTION_SEGMENT_2 2

OPCODE_DEFINE 008h   ; RRC B
xchg  ax, bp
ror   ah, 1
xchg  ax, bp
LOAD_NEXT_INSTRUCTION_SEGMENT_2 2

OPCODE_DEFINE 009h   ; RRC C
xchg  ax, bp
ror   al, 1
xchg  ax, bp
LOAD_NEXT_INSTRUCTION_SEGMENT_2 2

OPCODE_DEFINE 00Ah   ; RRC D
ror   dh, 1
LOAD_NEXT_INSTRUCTION_SEGMENT_2 2

OPCODE_DEFINE 00Bh   ; RRC E
ror   dl, 1
LOAD_NEXT_INSTRUCTION_SEGMENT_2 2

OPCODE_DEFINE 00Ch   ; RRC H
ror   bh, 1
LOAD_NEXT_INSTRUCTION_SEGMENT_2 2

OPCODE_DEFINE 00Dh   ; RRC L
ror   bl, 1
LOAD_NEXT_INSTRUCTION_SEGMENT_2 2

OPCODE_DEFINE 00Eh   ; RRC (HL)
ror   byte ptr ds:[bx], 1
LOAD_NEXT_INSTRUCTION_SEGMENT_2 4

OPCODE_DEFINE 00Fh   ; RRC A
ror   cl, 1
LOAD_NEXT_INSTRUCTION_SEGMENT_2 2

OPCODE_DEFINE 010h   ; RL B
xchg  ax, bp
rcl   ah, 1
xchg  ax, bp
LOAD_NEXT_INSTRUCTION_SEGMENT_2 2

OPCODE_DEFINE 011h   ; RL C
xchg  ax, bp
rcl   al, 1
xchg  ax, bp
LOAD_NEXT_INSTRUCTION_SEGMENT_2 2

OPCODE_DEFINE 012h   ; RL D
rcl   dh, 1
LOAD_NEXT_INSTRUCTION_SEGMENT_2 2

OPCODE_DEFINE 013h   ; RL E
rcl   dl, 1
LOAD_NEXT_INSTRUCTION_SEGMENT_2 2

OPCODE_DEFINE 014h   ; RL H
rcl   bh, 1
LOAD_NEXT_INSTRUCTION_SEGMENT_2 2

OPCODE_DEFINE 015h   ; RL L
rcl   bl, 1
LOAD_NEXT_INSTRUCTION_SEGMENT_2 2

OPCODE_DEFINE 016h   ; RL (HL)
rcl   byte ptr ds:[bx], 1
LOAD_NEXT_INSTRUCTION_SEGMENT_2 4

OPCODE_DEFINE 017h   ; RL A
rcl   cl, 1
LOAD_NEXT_INSTRUCTION_SEGMENT_2 2

OPCODE_DEFINE 018h   ; RR B
xchg  ax, bp
rcr   ah, 1
xchg  ax, bp
LOAD_NEXT_INSTRUCTION_SEGMENT_2 2

OPCODE_DEFINE 019h   ; RR C
xchg  ax, bp
rcr   al, 1
xchg  ax, bp
LOAD_NEXT_INSTRUCTION_SEGMENT_2 2

OPCODE_DEFINE 01Ah   ; RR D
rcr   dh, 1
LOAD_NEXT_INSTRUCTION_SEGMENT_2 2

OPCODE_DEFINE 01Bh   ; RR E
rcr   dl, 1
LOAD_NEXT_INSTRUCTION_SEGMENT_2 2

OPCODE_DEFINE 01Ch   ; RR H
rcr   bh, 1
LOAD_NEXT_INSTRUCTION_SEGMENT_2 2

OPCODE_DEFINE 01Dh   ; RR L
rcr   bl, 1
LOAD_NEXT_INSTRUCTION_SEGMENT_2 2

OPCODE_DEFINE 01Eh   ; RR (HL)
rcr   byte ptr ds:[bx], 1
LOAD_NEXT_INSTRUCTION_SEGMENT_2 4

OPCODE_DEFINE 01Fh   ; RR A
rcr   cl, 1
LOAD_NEXT_INSTRUCTION_SEGMENT_2 2

OPCODE_DEFINE 020h   ; SLA B
xchg  ax, bp
shl   ah, 1
xchg  ax, bp
LOAD_NEXT_INSTRUCTION_SEGMENT_2 2

OPCODE_DEFINE 021h   ; SLA C
xchg  ax, bp
shl   al, 1
xchg  ax, bp
LOAD_NEXT_INSTRUCTION_SEGMENT_2 2

OPCODE_DEFINE 022h   ; SLA D
shl   dh, 1
LOAD_NEXT_INSTRUCTION_SEGMENT_2 2

OPCODE_DEFINE 023h   ; SLA E
shl   dl, 1
LOAD_NEXT_INSTRUCTION_SEGMENT_2 2

OPCODE_DEFINE 024h   ; SLA H
shl   bh, 1
LOAD_NEXT_INSTRUCTION_SEGMENT_2 2

OPCODE_DEFINE 025h   ; SLA L
shl   bl, 1
LOAD_NEXT_INSTRUCTION_SEGMENT_2 2

OPCODE_DEFINE 026h   ; SLA (HL)
shl   byte ptr ds:[bx], 1
LOAD_NEXT_INSTRUCTION_SEGMENT_2 4

OPCODE_DEFINE 027h   ; SLA A
shl   cl, 1
LOAD_NEXT_INSTRUCTION_SEGMENT_2 2

OPCODE_DEFINE 028h   ; SRA B
xchg  ax, bp
sar   ah, 1
xchg  ax, bp
LOAD_NEXT_INSTRUCTION_SEGMENT_2 2

OPCODE_DEFINE 029h   ; SRA C
xchg  ax, bp
sar   al, 1
xchg  ax, bp
LOAD_NEXT_INSTRUCTION_SEGMENT_2 2

OPCODE_DEFINE 02Ah   ; SRA D
sar   dh, 1
LOAD_NEXT_INSTRUCTION_SEGMENT_2 2

OPCODE_DEFINE 02Bh   ; SRA E
sar   dl, 1
LOAD_NEXT_INSTRUCTION_SEGMENT_2 2

OPCODE_DEFINE 02Ch   ; SRA H
sar   bh, 1
LOAD_NEXT_INSTRUCTION_SEGMENT_2 2

OPCODE_DEFINE 02Dh   ; SRA L
sar   bl, 1
LOAD_NEXT_INSTRUCTION_SEGMENT_2 2

OPCODE_DEFINE 02Eh   ; SRA (HL)
sar   byte ptr ds:[bx], 1
LOAD_NEXT_INSTRUCTION_SEGMENT_2 4

OPCODE_DEFINE 02Fh   ; SRA A
sar   cl, 1
LOAD_NEXT_INSTRUCTION_SEGMENT_2 2

OPCODE_DEFINE 030h   ; SWAP B
lahf
xchg  ax, bp
ROL4_MACRO ah
xchg  ax, bp
sahf
LOAD_NEXT_INSTRUCTION_SEGMENT_2 2

OPCODE_DEFINE 031h   ; SWAP C
lahf
xchg  ax, bp
ROL4_MACRO al
xchg  ax, bp
sahf
LOAD_NEXT_INSTRUCTION_SEGMENT_2 2

OPCODE_DEFINE 032h   ; SWAP D
lahf
ROL4_MACRO bl
sahf
LOAD_NEXT_INSTRUCTION_SEGMENT_2 2

OPCODE_DEFINE 033h   ; SWAP E
lahf
ROL4_MACRO dl
sahf
LOAD_NEXT_INSTRUCTION_SEGMENT_2 2

OPCODE_DEFINE 034h   ; SWAP H
lahf
ROL4_MACRO bh
sahf
LOAD_NEXT_INSTRUCTION_SEGMENT_2 2

OPCODE_DEFINE 035h   ; SWAP L
lahf
ROL4_MACRO bl
sahf
LOAD_NEXT_INSTRUCTION_SEGMENT_2 2

OPCODE_DEFINE 036h   ; SWAP (HL)
lahf
mov   al, byte ptr ds:[bx]
ROL4_MACRO al
mov   byte ptr ds:[bx], al
sahf
LOAD_NEXT_INSTRUCTION_SEGMENT_2 4

OPCODE_DEFINE 037h   ; SWAP A
lahf
ROL4_MACRO cl
sahf
LOAD_NEXT_INSTRUCTION_SEGMENT_2 2


OPCODE_DEFINE 038h   ; SRL B
xchg  ax, bp
shr   ah, 1
xchg  ax, bp
LOAD_NEXT_INSTRUCTION_SEGMENT_2 2

OPCODE_DEFINE 039h   ; SRL C
xchg  ax, bp
shr   al, 1
xchg  ax, bp
LOAD_NEXT_INSTRUCTION_SEGMENT_2 2

OPCODE_DEFINE 03Ah   ; SRL D
shr   dh, 1
LOAD_NEXT_INSTRUCTION_SEGMENT_2 2

OPCODE_DEFINE 03Bh   ; SRL E
shr   dl, 1
LOAD_NEXT_INSTRUCTION_SEGMENT_2 2

OPCODE_DEFINE 03Ch   ; SRL H
shr   bh, 1
LOAD_NEXT_INSTRUCTION_SEGMENT_2 2

OPCODE_DEFINE 03Dh   ; SRL L
shr   bl, 1
LOAD_NEXT_INSTRUCTION_SEGMENT_2 2

OPCODE_DEFINE 03Eh   ; SRL (HL)
shr   byte ptr ds:[bx], 1
LOAD_NEXT_INSTRUCTION_SEGMENT_2 4

OPCODE_DEFINE 03Fh   ; SRL A
shr   cl, 1
LOAD_NEXT_INSTRUCTION_SEGMENT_2 2

OPCODE_DEFINE 040h   ; BIT 0, B
test  bp, ((1 SHL 0) SHL 8)
LOAD_NEXT_INSTRUCTION_SEGMENT_2 2

OPCODE_DEFINE 041h   ; BIT 0, C
test  bp, (1 SHL 0)
LOAD_NEXT_INSTRUCTION_SEGMENT_2 2

OPCODE_DEFINE 042h   ; BIT 0, D
test  dh, (1 SHL 0)
LOAD_NEXT_INSTRUCTION_SEGMENT_2 2

OPCODE_DEFINE 043h   ; BIT 0, E
test  dl, (1 SHL 0)
LOAD_NEXT_INSTRUCTION_SEGMENT_2 2

OPCODE_DEFINE 044h   ; BIT 0, H
test  bh, (1 SHL 0)
LOAD_NEXT_INSTRUCTION_SEGMENT_2 2

OPCODE_DEFINE 045h   ; BIT 0, L
test  bl, (1 SHL 0)
LOAD_NEXT_INSTRUCTION_SEGMENT_2 2

OPCODE_DEFINE 046h   ; BIT 0, (HL)
test  byte ptr ds:[bx], (1 SHL 0)
LOAD_NEXT_INSTRUCTION_SEGMENT_2 3

OPCODE_DEFINE 047h   ; BIT 0, A
test  cl, (1 SHL 0)
LOAD_NEXT_INSTRUCTION_SEGMENT_2 2

OPCODE_DEFINE 048h   ; BIT 1, B
test  bp, ((1 SHL 1) SHL 8)
LOAD_NEXT_INSTRUCTION_SEGMENT_2 2

OPCODE_DEFINE 049h   ; BIT 1, C
test  bp, (1 SHL 1)
LOAD_NEXT_INSTRUCTION_SEGMENT_2 2

OPCODE_DEFINE 04Ah   ; BIT 1, D
test  dh, (1 SHL 1)
LOAD_NEXT_INSTRUCTION_SEGMENT_2 2

OPCODE_DEFINE 04Bh   ; BIT 1, E
test  dl, (1 SHL 1)
LOAD_NEXT_INSTRUCTION_SEGMENT_2 2

OPCODE_DEFINE 04Ch   ; BIT 1, H
test  bh, (1 SHL 1)
LOAD_NEXT_INSTRUCTION_SEGMENT_2 2

OPCODE_DEFINE 04Dh   ; BIT 1, L
test  bl, (1 SHL 1)
LOAD_NEXT_INSTRUCTION_SEGMENT_2 2

OPCODE_DEFINE 04Eh   ; BIT 1, (HL)
test  byte ptr ds:[bx], (1 SHL 1)
LOAD_NEXT_INSTRUCTION_SEGMENT_2 3

OPCODE_DEFINE 04Fh   ; BIT 1, A
test  cl, (1 SHL 1)
LOAD_NEXT_INSTRUCTION_SEGMENT_2 2

OPCODE_DEFINE 050h   ; BIT 2, B
test  bp, ((1 SHL 2) SHL 8)
LOAD_NEXT_INSTRUCTION_SEGMENT_2 2

OPCODE_DEFINE 051h   ; BIT 2, C
test  bp, (1 SHL 2)
LOAD_NEXT_INSTRUCTION_SEGMENT_2 2

OPCODE_DEFINE 052h   ; BIT 2, D
test  dh, (1 SHL 2)
LOAD_NEXT_INSTRUCTION_SEGMENT_2 2

OPCODE_DEFINE 053h   ; BIT 2, E
test  dl, (1 SHL 2)
LOAD_NEXT_INSTRUCTION_SEGMENT_2 2

OPCODE_DEFINE 054h   ; BIT 2, H
test  bh, (1 SHL 2)
LOAD_NEXT_INSTRUCTION_SEGMENT_2 2

OPCODE_DEFINE 055h   ; BIT 2, L
test  bl, (1 SHL 2)
LOAD_NEXT_INSTRUCTION_SEGMENT_2 2

OPCODE_DEFINE 056h   ; BIT 2, (HL)
test  byte ptr ds:[bx], (1 SHL 2)
LOAD_NEXT_INSTRUCTION_SEGMENT_2 3

OPCODE_DEFINE 057h   ; BIT 2, A
test  cl, (1 SHL 2)
LOAD_NEXT_INSTRUCTION_SEGMENT_2 2

OPCODE_DEFINE 058h   ; BIT 3, B
test  bp, ((1 SHL 3) SHL 8)
LOAD_NEXT_INSTRUCTION_SEGMENT_2 2

OPCODE_DEFINE 059h   ; BIT 3, C
test  bp, (1 SHL 3)
LOAD_NEXT_INSTRUCTION_SEGMENT_2 2

OPCODE_DEFINE 05Ah   ; BIT 3, D
test  dh, (1 SHL 3)
LOAD_NEXT_INSTRUCTION_SEGMENT_2 2

OPCODE_DEFINE 05Bh   ; BIT 3, E
test  dl, (1 SHL 3)
LOAD_NEXT_INSTRUCTION_SEGMENT_2 2

OPCODE_DEFINE 05Ch   ; BIT 3, H
test  bh, (1 SHL 3)
LOAD_NEXT_INSTRUCTION_SEGMENT_2 2

OPCODE_DEFINE 05Dh   ; BIT 3, L
test  bl, (1 SHL 3)
LOAD_NEXT_INSTRUCTION_SEGMENT_2 2

OPCODE_DEFINE 05Eh   ; BIT 3, (HL)
test  byte ptr ds:[bx], (1 SHL 3)
LOAD_NEXT_INSTRUCTION_SEGMENT_2 3

OPCODE_DEFINE 05Fh   ; BIT 3, A
test  cl, (1 SHL 3)
LOAD_NEXT_INSTRUCTION_SEGMENT_2 2

OPCODE_DEFINE 060h   ; BIT 4, B
test  bp, ((1 SHL 4) SHL 8)
LOAD_NEXT_INSTRUCTION_SEGMENT_2 2

OPCODE_DEFINE 061h   ; BIT 4, C
test  bp, (1 SHL 4)
LOAD_NEXT_INSTRUCTION_SEGMENT_2 2

OPCODE_DEFINE 062h   ; BIT 4, D
test  dh, (1 SHL 4)
LOAD_NEXT_INSTRUCTION_SEGMENT_2 2

OPCODE_DEFINE 063h   ; BIT 4, E
test  dl, (1 SHL 4)
LOAD_NEXT_INSTRUCTION_SEGMENT_2 2

OPCODE_DEFINE 064h   ; BIT 4, H
test  bh, (1 SHL 4)
LOAD_NEXT_INSTRUCTION_SEGMENT_2 2

OPCODE_DEFINE 065h   ; BIT 4, L
test  bl, (1 SHL 4)
LOAD_NEXT_INSTRUCTION_SEGMENT_2 2

OPCODE_DEFINE 066h   ; BIT 4, (HL)
test  byte ptr ds:[bx], (1 SHL 4)
LOAD_NEXT_INSTRUCTION_SEGMENT_2 3

OPCODE_DEFINE 067h   ; BIT 4, A
test  cl, (1 SHL 4)
LOAD_NEXT_INSTRUCTION_SEGMENT_2 2

OPCODE_DEFINE 068h   ; BIT 5, B
test  bp, ((1 SHL 5) SHL 8)
LOAD_NEXT_INSTRUCTION_SEGMENT_2 2

OPCODE_DEFINE 069h   ; BIT 5, C
test  bp, (1 SHL 5)
LOAD_NEXT_INSTRUCTION_SEGMENT_2 2

OPCODE_DEFINE 06Ah   ; BIT 5, D
test  dh, (1 SHL 5)
LOAD_NEXT_INSTRUCTION_SEGMENT_2 2

OPCODE_DEFINE 06Bh   ; BIT 5, E
test  dl, (1 SHL 5)
LOAD_NEXT_INSTRUCTION_SEGMENT_2 2

OPCODE_DEFINE 06Ch   ; BIT 5, H
test  bh, (1 SHL 5)
LOAD_NEXT_INSTRUCTION_SEGMENT_2 2

OPCODE_DEFINE 06Dh   ; BIT 5, L
test  bl, (1 SHL 5)
LOAD_NEXT_INSTRUCTION_SEGMENT_2 2

OPCODE_DEFINE 06Eh   ; BIT 5, (HL)
test  byte ptr ds:[bx], (1 SHL 5)
LOAD_NEXT_INSTRUCTION_SEGMENT_2 3

OPCODE_DEFINE 06Fh   ; BIT 5, A
test  cl, (1 SHL 5)
LOAD_NEXT_INSTRUCTION_SEGMENT_2 2

OPCODE_DEFINE 070h   ; BIT 6, B
test  bp, ((1 SHL 6) SHL 8)
LOAD_NEXT_INSTRUCTION_SEGMENT_2 2

OPCODE_DEFINE 071h   ; BIT 6, C
test  bp, (1 SHL 6)
LOAD_NEXT_INSTRUCTION_SEGMENT_2 2

OPCODE_DEFINE 072h   ; BIT 6, D
test  dh, (1 SHL 6)
LOAD_NEXT_INSTRUCTION_SEGMENT_2 2

OPCODE_DEFINE 073h   ; BIT 6, E
test  dl, (1 SHL 6)
LOAD_NEXT_INSTRUCTION_SEGMENT_2 2

OPCODE_DEFINE 074h   ; BIT 6, H
test  bh, (1 SHL 6)
LOAD_NEXT_INSTRUCTION_SEGMENT_2 2

OPCODE_DEFINE 075h   ; BIT 6, L
test  bl, (1 SHL 6)
LOAD_NEXT_INSTRUCTION_SEGMENT_2 2

OPCODE_DEFINE 076h   ; BIT 6, (HL)
test  byte ptr ds:[bx], (1 SHL 6)
LOAD_NEXT_INSTRUCTION_SEGMENT_2 3

OPCODE_DEFINE 077h   ; BIT 6, A
test  cl, (1 SHL 6)
LOAD_NEXT_INSTRUCTION_SEGMENT_2 2

OPCODE_DEFINE 078h   ; BIT 7, B
test  bp, ((1 SHL 7) SHL 8)
LOAD_NEXT_INSTRUCTION_SEGMENT_2 2

OPCODE_DEFINE 079h   ; BIT 7, C
test  bp, (1 SHL 7)
LOAD_NEXT_INSTRUCTION_SEGMENT_2 2

OPCODE_DEFINE 07Ah   ; BIT 7, D
test  dh, (1 SHL 7)
LOAD_NEXT_INSTRUCTION_SEGMENT_2 2

OPCODE_DEFINE 07Bh   ; BIT 7, E
test  dl, (1 SHL 7)
LOAD_NEXT_INSTRUCTION_SEGMENT_2 2

OPCODE_DEFINE 07Ch   ; BIT 7, H
test  bh, (1 SHL 7)
LOAD_NEXT_INSTRUCTION_SEGMENT_2 2

OPCODE_DEFINE 07Dh   ; BIT 7, L
test  bl, (1 SHL 7)
LOAD_NEXT_INSTRUCTION_SEGMENT_2 2

OPCODE_DEFINE 07Eh   ; BIT 7, (HL)
test  byte ptr ds:[bx], (1 SHL 7)
LOAD_NEXT_INSTRUCTION_SEGMENT_2 3

OPCODE_DEFINE 07Fh   ; BIT 7, A
test  cl, (1 SHL 7)
LOAD_NEXT_INSTRUCTION_SEGMENT_2 2


OPCODE_DEFINE 080h   ; RES 0, B
lahf
and   bp, (NOT ((1 SHL 0) SHL 8))
sahf
LOAD_NEXT_INSTRUCTION_SEGMENT_2 2

OPCODE_DEFINE 081h   ; RES 0, C
lahf
and   bp, (NOT (1 SHL 0))
sahf
LOAD_NEXT_INSTRUCTION_SEGMENT_2 2

OPCODE_DEFINE 082h   ; RES 0, D
lahf
and   dh, (NOT (1 SHL 0))
sahf
LOAD_NEXT_INSTRUCTION_SEGMENT_2 2

OPCODE_DEFINE 083h   ; RES 0, E
lahf
and   dl, (NOT (1 SHL 0))
sahf
LOAD_NEXT_INSTRUCTION_SEGMENT_2 2

OPCODE_DEFINE 084h   ; RES 0, H
lahf
and   bh, (NOT (1 SHL 0))
sahf
LOAD_NEXT_INSTRUCTION_SEGMENT_2 2

OPCODE_DEFINE 085h   ; RES 0, L
lahf
and   bl, (NOT (1 SHL 0))
sahf
LOAD_NEXT_INSTRUCTION_SEGMENT_2 2

OPCODE_DEFINE 086h   ; RES 0, (HL)
lahf
and   byte ptr ds:[bx], (NOT (1 SHL 0))
sahf
LOAD_NEXT_INSTRUCTION_SEGMENT_2 4

OPCODE_DEFINE 087h   ; RES 0, A
lahf
and   cl, (NOT (1 SHL 0))
sahf
LOAD_NEXT_INSTRUCTION_SEGMENT_2 2

OPCODE_DEFINE 088h   ; RES 1, B
lahf
and   bp, (NOT ((1 SHL 1) SHL 8))
sahf
LOAD_NEXT_INSTRUCTION_SEGMENT_2 2

OPCODE_DEFINE 089h   ; RES 1, C
lahf
and   bp, (NOT (1 SHL 1))
sahf
LOAD_NEXT_INSTRUCTION_SEGMENT_2 2

OPCODE_DEFINE 08Ah   ; RES 1, D
lahf
and   dh, (NOT (1 SHL 1))
sahf
LOAD_NEXT_INSTRUCTION_SEGMENT_2 2

OPCODE_DEFINE 08Bh   ; RES 1, E
lahf
and   dl, (NOT (1 SHL 1))
sahf
LOAD_NEXT_INSTRUCTION_SEGMENT_2 2

OPCODE_DEFINE 08Ch   ; RES 1, H
lahf
and   bh, (NOT (1 SHL 1))
sahf
LOAD_NEXT_INSTRUCTION_SEGMENT_2 2

OPCODE_DEFINE 08Dh   ; RES 1, L
lahf
and   bl, (NOT (1 SHL 1))
sahf
LOAD_NEXT_INSTRUCTION_SEGMENT_2 2

OPCODE_DEFINE 08Eh   ; RES 1, (HL)
lahf
and   byte ptr ds:[bx], (NOT (1 SHL 1))
sahf
LOAD_NEXT_INSTRUCTION_SEGMENT_2 4

OPCODE_DEFINE 08Fh   ; RES 1, A
lahf
and   cl, (NOT (1 SHL 1))
sahf
LOAD_NEXT_INSTRUCTION_SEGMENT_2 2

OPCODE_DEFINE 090h   ; RES 2, B
lahf
and   bp, (NOT ((1 SHL 2) SHL 8))
sahf
LOAD_NEXT_INSTRUCTION_SEGMENT_2 2

OPCODE_DEFINE 091h   ; RES 2, C
lahf
and   bp, (NOT (1 SHL 2))
sahf
LOAD_NEXT_INSTRUCTION_SEGMENT_2 2

OPCODE_DEFINE 092h   ; RES 2, D
lahf
and   dh, (NOT (1 SHL 2))
sahf
LOAD_NEXT_INSTRUCTION_SEGMENT_2 2

OPCODE_DEFINE 093h   ; RES 2, E
lahf
and   dl, (NOT (1 SHL 2))
sahf
LOAD_NEXT_INSTRUCTION_SEGMENT_2 2

OPCODE_DEFINE 094h   ; RES 2, H
lahf
and   bh, (NOT (1 SHL 2))
sahf
LOAD_NEXT_INSTRUCTION_SEGMENT_2 2

OPCODE_DEFINE 095h   ; RES 2, L
lahf
and   bl, (NOT (1 SHL 2))
sahf
LOAD_NEXT_INSTRUCTION_SEGMENT_2 2

OPCODE_DEFINE 096h   ; RES 2, (HL)
lahf
and   byte ptr ds:[bx], (NOT (1 SHL 2))
sahf
LOAD_NEXT_INSTRUCTION_SEGMENT_2 4

OPCODE_DEFINE 097h   ; RES 2, A
lahf
and   cl, (NOT (1 SHL 2))
sahf
LOAD_NEXT_INSTRUCTION_SEGMENT_2 2

OPCODE_DEFINE 098h   ; RES 3, B
lahf
and   bp, (NOT ((1 SHL 3) SHL 8))
sahf
LOAD_NEXT_INSTRUCTION_SEGMENT_2 2

OPCODE_DEFINE 099h   ; RES 3, C
lahf
and   bp, (NOT (1 SHL 3))
sahf
LOAD_NEXT_INSTRUCTION_SEGMENT_2 2

OPCODE_DEFINE 09Ah   ; RES 3, D
lahf
and   dh, (NOT (1 SHL 3))
sahf
LOAD_NEXT_INSTRUCTION_SEGMENT_2 2

OPCODE_DEFINE 09Bh   ; RES 3, E
lahf
and   dl, (NOT (1 SHL 3))
sahf
LOAD_NEXT_INSTRUCTION_SEGMENT_2 2

OPCODE_DEFINE 09Ch   ; RES 3, H
lahf
and   bh, (NOT (1 SHL 3))
sahf
LOAD_NEXT_INSTRUCTION_SEGMENT_2 2

OPCODE_DEFINE 09Dh   ; RES 3, L
lahf
and   bl, (NOT (1 SHL 3))
sahf
LOAD_NEXT_INSTRUCTION_SEGMENT_2 2

OPCODE_DEFINE 09Eh   ; RES 3, (HL)
lahf
and   byte ptr ds:[bx], (NOT (1 SHL 3))
sahf
LOAD_NEXT_INSTRUCTION_SEGMENT_2 4

OPCODE_DEFINE 09Fh   ; RES 3, A
lahf
and   cl, (NOT (1 SHL 3))
sahf
LOAD_NEXT_INSTRUCTION_SEGMENT_2 2

OPCODE_DEFINE 0A0h   ; RES 4, B
lahf
and   bp, (NOT ((1 SHL 4) SHL 8))
sahf
LOAD_NEXT_INSTRUCTION_SEGMENT_2 2

OPCODE_DEFINE 0A1h   ; RES 4, C
lahf
and   bp, (NOT (1 SHL 4))
sahf
LOAD_NEXT_INSTRUCTION_SEGMENT_2 2

OPCODE_DEFINE 0A2h   ; RES 4, D
lahf
and   dh, (NOT (1 SHL 4))
sahf
LOAD_NEXT_INSTRUCTION_SEGMENT_2 2

OPCODE_DEFINE 0A3h   ; RES 4, E
lahf
and   dl, (NOT (1 SHL 4))
sahf
LOAD_NEXT_INSTRUCTION_SEGMENT_2 2

OPCODE_DEFINE 0A4h   ; RES 4, H
lahf
and   bh, (NOT (1 SHL 4))
sahf
LOAD_NEXT_INSTRUCTION_SEGMENT_2 2

OPCODE_DEFINE 0A5h   ; RES 4, L
lahf
and   bl, (NOT (1 SHL 4))
sahf
LOAD_NEXT_INSTRUCTION_SEGMENT_2 2

OPCODE_DEFINE 0A6h   ; RES 4, (HL)
lahf
and   byte ptr ds:[bx], (NOT (1 SHL 4))
sahf
LOAD_NEXT_INSTRUCTION_SEGMENT_2 4

OPCODE_DEFINE 0A7h   ; RES 4, A
lahf
and   cl, (NOT (1 SHL 4))
sahf
LOAD_NEXT_INSTRUCTION_SEGMENT_2 2

OPCODE_DEFINE 0A8h   ; RES 5, B
lahf
and   bp, (NOT ((1 SHL 5) SHL 8))
sahf
LOAD_NEXT_INSTRUCTION_SEGMENT_2 2

OPCODE_DEFINE 0A9h   ; RES 5, C
lahf
and   bp, (NOT (1 SHL 5))
sahf
LOAD_NEXT_INSTRUCTION_SEGMENT_2 2

OPCODE_DEFINE 0AAh   ; RES 5, D
lahf
and   dh, (NOT (1 SHL 5))
sahf
LOAD_NEXT_INSTRUCTION_SEGMENT_2 2

OPCODE_DEFINE 0ABh   ; RES 5, E
lahf
and   dl, (NOT (1 SHL 5))
sahf
LOAD_NEXT_INSTRUCTION_SEGMENT_2 2

OPCODE_DEFINE 0ACh   ; RES 5, H
lahf
and   bh, (NOT (1 SHL 5))
sahf
LOAD_NEXT_INSTRUCTION_SEGMENT_2 2

OPCODE_DEFINE 0ADh   ; RES 5, L
lahf
and   bl, (NOT (1 SHL 5))
sahf
LOAD_NEXT_INSTRUCTION_SEGMENT_2 2

OPCODE_DEFINE 0AEh   ; RES 5, (HL)
lahf
and   byte ptr ds:[bx], (NOT (1 SHL 5))
sahf
LOAD_NEXT_INSTRUCTION_SEGMENT_2 4

OPCODE_DEFINE 0AFh   ; RES 5, A
lahf
and   cl, (NOT (1 SHL 5))
sahf
LOAD_NEXT_INSTRUCTION_SEGMENT_2 2

OPCODE_DEFINE 0B0h   ; RES 6, B
lahf
and   bp, (NOT ((1 SHL 6) SHL 8))
sahf
LOAD_NEXT_INSTRUCTION_SEGMENT_2 2

OPCODE_DEFINE 0B1h   ; RES 6, C
lahf
and   bp, (NOT (1 SHL 6))
sahf
LOAD_NEXT_INSTRUCTION_SEGMENT_2 2

OPCODE_DEFINE 0B2h   ; RES 6, D
lahf
and   dh, (NOT (1 SHL 6))
sahf
LOAD_NEXT_INSTRUCTION_SEGMENT_2 2

OPCODE_DEFINE 0B3h   ; RES 6, E
lahf
and   dl, (NOT (1 SHL 6))
sahf
LOAD_NEXT_INSTRUCTION_SEGMENT_2 2

OPCODE_DEFINE 0B4h   ; RES 6, H
lahf
and   bh, (NOT (1 SHL 6))
sahf
LOAD_NEXT_INSTRUCTION_SEGMENT_2 2

OPCODE_DEFINE 0B5h   ; RES 6, L
lahf
and   bl, (NOT (1 SHL 6))
sahf
LOAD_NEXT_INSTRUCTION_SEGMENT_2 2

OPCODE_DEFINE 0B6h   ; RES 6, (HL)
lahf
and   byte ptr ds:[bx], (NOT (1 SHL 6))
sahf
LOAD_NEXT_INSTRUCTION_SEGMENT_2 4

OPCODE_DEFINE 0B7h   ; RES 6, A
lahf
and   cl, (NOT (1 SHL 6))
sahf
LOAD_NEXT_INSTRUCTION_SEGMENT_2 2

OPCODE_DEFINE 0B8h   ; RES 7, B
lahf
and   bp, (NOT ((1 SHL 7) SHL 8))
sahf
LOAD_NEXT_INSTRUCTION_SEGMENT_2 2

OPCODE_DEFINE 0B9h   ; RES 7, C
lahf
and   bp, (NOT (1 SHL 7))
sahf
LOAD_NEXT_INSTRUCTION_SEGMENT_2 2

OPCODE_DEFINE 0BAh   ; RES 7, D
lahf
and   dh, (NOT (1 SHL 7))
sahf
LOAD_NEXT_INSTRUCTION_SEGMENT_2 2

OPCODE_DEFINE 0BBh   ; RES 7, E
lahf
and   dl, (NOT (1 SHL 7))
sahf
LOAD_NEXT_INSTRUCTION_SEGMENT_2 2

OPCODE_DEFINE 0BCh   ; RES 7, H
lahf
and   bh, (NOT (1 SHL 7))
sahf
LOAD_NEXT_INSTRUCTION_SEGMENT_2 2

OPCODE_DEFINE 0BDh   ; RES 7, L
lahf
and   bl, (NOT (1 SHL 7))
sahf
LOAD_NEXT_INSTRUCTION_SEGMENT_2 2

OPCODE_DEFINE 0BEh   ; RES 7, (HL)
lahf
and   byte ptr ds:[bx], (NOT (1 SHL 7))
sahf
LOAD_NEXT_INSTRUCTION_SEGMENT_2 4

OPCODE_DEFINE 0BFh   ; RES 7, A
lahf
and   cl, (NOT (1 SHL 7))
sahf
LOAD_NEXT_INSTRUCTION_SEGMENT_2 2

OPCODE_DEFINE 0C0h   ; SET 0, B
lahf
or    bp, ( (1 SHL 0) SHL 8)
sahf
LOAD_NEXT_INSTRUCTION_SEGMENT_2 2

OPCODE_DEFINE 0C1h   ; SET 0, C
lahf
or    bp, (1 SHL 0)
sahf
LOAD_NEXT_INSTRUCTION_SEGMENT_2 2

OPCODE_DEFINE 0C2h   ; SET 0, D
lahf
or    dh, (1 SHL 0)
sahf
LOAD_NEXT_INSTRUCTION_SEGMENT_2 2

OPCODE_DEFINE 0C3h   ; SET 0, E
lahf
or    dl, (1 SHL 0)
sahf
LOAD_NEXT_INSTRUCTION_SEGMENT_2 2

OPCODE_DEFINE 0C4h   ; SET 0, H
lahf
or    bh, (1 SHL 0)
sahf
LOAD_NEXT_INSTRUCTION_SEGMENT_2 2

OPCODE_DEFINE 0C5h   ; SET 0, L
lahf
or    bl, (1 SHL 0)
sahf
LOAD_NEXT_INSTRUCTION_SEGMENT_2 2

OPCODE_DEFINE 0C6h   ; SET 0, (HL)
lahf
or    byte ptr ds:[bx],  (1 SHL 0)
sahf
LOAD_NEXT_INSTRUCTION_SEGMENT_2 4

OPCODE_DEFINE 0C7h   ; SET 0, A
lahf
or    cl, (1 SHL 0)
sahf
LOAD_NEXT_INSTRUCTION_SEGMENT_2 2

OPCODE_DEFINE 0C8h   ; SET 1, B
lahf
or    bp, ( (1 SHL 1) SHL 8)
sahf
LOAD_NEXT_INSTRUCTION_SEGMENT_2 2

OPCODE_DEFINE 0C9h   ; SET 1, C
lahf
or    bp, (1 SHL 1)
sahf
LOAD_NEXT_INSTRUCTION_SEGMENT_2 2

OPCODE_DEFINE 0CAh   ; SET 1, D
lahf
or    dh, (1 SHL 1)
sahf
LOAD_NEXT_INSTRUCTION_SEGMENT_2 2

OPCODE_DEFINE 0CBh   ; SET 1, E
lahf
or    dl, (1 SHL 1)
sahf
LOAD_NEXT_INSTRUCTION_SEGMENT_2 2

OPCODE_DEFINE 0CCh   ; SET 1, H
lahf
or    bh, (1 SHL 1)
sahf
LOAD_NEXT_INSTRUCTION_SEGMENT_2 2

OPCODE_DEFINE 0CDh   ; SET 1, L
lahf
or    bl, (1 SHL 1)
sahf
LOAD_NEXT_INSTRUCTION_SEGMENT_2 2

OPCODE_DEFINE 0CEh   ; SET 1, (HL)
lahf
or    byte ptr ds:[bx],  (1 SHL 1)
sahf
LOAD_NEXT_INSTRUCTION_SEGMENT_2 4

OPCODE_DEFINE 0CFh   ; SET 1, A
lahf
or    cl, (1 SHL 1)
sahf
LOAD_NEXT_INSTRUCTION_SEGMENT_2 2

OPCODE_DEFINE 0D0h   ; SET 2, B
lahf
or    bp, ( (1 SHL 2) SHL 8)
sahf
LOAD_NEXT_INSTRUCTION_SEGMENT_2 2

OPCODE_DEFINE 0D1h   ; SET 2, C
lahf
or    bp, (1 SHL 2)
sahf
LOAD_NEXT_INSTRUCTION_SEGMENT_2 2

OPCODE_DEFINE 0D2h   ; SET 2, D
lahf
or    dh, (1 SHL 2)
sahf
LOAD_NEXT_INSTRUCTION_SEGMENT_2 2

OPCODE_DEFINE 0D3h   ; SET 2, E
lahf
or    dl, (1 SHL 2)
sahf
LOAD_NEXT_INSTRUCTION_SEGMENT_2 2

OPCODE_DEFINE 0D4h   ; SET 2, H
lahf
or    bh, (1 SHL 2)
sahf
LOAD_NEXT_INSTRUCTION_SEGMENT_2 2

OPCODE_DEFINE 0D5h   ; SET 2, L
lahf
or    bl, (1 SHL 2)
sahf
LOAD_NEXT_INSTRUCTION_SEGMENT_2 2

OPCODE_DEFINE 0D6h   ; SET 2, (HL)
lahf
or    byte ptr ds:[bx],  (1 SHL 2)
sahf
LOAD_NEXT_INSTRUCTION_SEGMENT_2 4

OPCODE_DEFINE 0D7h   ; SET 2, A
lahf
or    cl, (1 SHL 2)
sahf
LOAD_NEXT_INSTRUCTION_SEGMENT_2 2

OPCODE_DEFINE 0D8h   ; SET 3, B
lahf
or    bp, ( (1 SHL 3) SHL 8)
sahf
LOAD_NEXT_INSTRUCTION_SEGMENT_2 2

OPCODE_DEFINE 0D9h   ; SET 3, C
lahf
or    bp, (1 SHL 3)
sahf
LOAD_NEXT_INSTRUCTION_SEGMENT_2 2

OPCODE_DEFINE 0DAh   ; SET 3, D
lahf
or    dh, (1 SHL 3)
sahf
LOAD_NEXT_INSTRUCTION_SEGMENT_2 2

OPCODE_DEFINE 0DBh   ; SET 3, E
lahf
or    dl, (1 SHL 3)
sahf
LOAD_NEXT_INSTRUCTION_SEGMENT_2 2

OPCODE_DEFINE 0DCh   ; SET 3, H
lahf
or    bh, (1 SHL 3)
sahf
LOAD_NEXT_INSTRUCTION_SEGMENT_2 2

OPCODE_DEFINE 0DDh   ; SET 3, L
lahf
or    bl, (1 SHL 3)
sahf
LOAD_NEXT_INSTRUCTION_SEGMENT_2 2

OPCODE_DEFINE 0DEh   ; SET 3, (HL)
lahf
or    byte ptr ds:[bx],  (1 SHL 3)
sahf
LOAD_NEXT_INSTRUCTION_SEGMENT_2 4

OPCODE_DEFINE 0DFh   ; SET 3, A
lahf
or    cl, (1 SHL 3)
sahf
LOAD_NEXT_INSTRUCTION_SEGMENT_2 2

OPCODE_DEFINE 0E0h   ; SET 4, B
lahf
or    bp, ( (1 SHL 4) SHL 8)
sahf
LOAD_NEXT_INSTRUCTION_SEGMENT_2 2

OPCODE_DEFINE 0E1h   ; SET 4, C
lahf
or    bp, (1 SHL 4)
sahf
LOAD_NEXT_INSTRUCTION_SEGMENT_2 2

OPCODE_DEFINE 0E2h   ; SET 4, D
lahf
or    dh, (1 SHL 4)
sahf
LOAD_NEXT_INSTRUCTION_SEGMENT_2 2

OPCODE_DEFINE 0E3h   ; SET 4, E
lahf
or    dl, (1 SHL 4)
sahf
LOAD_NEXT_INSTRUCTION_SEGMENT_2 2

OPCODE_DEFINE 0E4h   ; SET 4, H
lahf
or    bh, (1 SHL 4)
sahf
LOAD_NEXT_INSTRUCTION_SEGMENT_2 2

OPCODE_DEFINE 0E5h   ; SET 4, L
lahf
or    bl, (1 SHL 4)
sahf
LOAD_NEXT_INSTRUCTION_SEGMENT_2 2

OPCODE_DEFINE 0E6h   ; SET 4, (HL)
lahf
or    byte ptr ds:[bx],  (1 SHL 4)
sahf
LOAD_NEXT_INSTRUCTION_SEGMENT_2 4

OPCODE_DEFINE 0E7h   ; SET 4, A
lahf
or    cl, (1 SHL 4)
sahf
LOAD_NEXT_INSTRUCTION_SEGMENT_2 2

OPCODE_DEFINE 0E8h   ; SET 5, B
lahf
or    bp, ( (1 SHL 5) SHL 8)
sahf
LOAD_NEXT_INSTRUCTION_SEGMENT_2 2

OPCODE_DEFINE 0E9h   ; SET 5, C
lahf
or    bp, (1 SHL 5)
sahf
LOAD_NEXT_INSTRUCTION_SEGMENT_2 2

OPCODE_DEFINE 0EAh   ; SET 5, D
lahf
or    dh, (1 SHL 5)
sahf
LOAD_NEXT_INSTRUCTION_SEGMENT_2 2

OPCODE_DEFINE 0EBh   ; SET 5, E
lahf
or    dl, (1 SHL 5)
sahf
LOAD_NEXT_INSTRUCTION_SEGMENT_2 2

OPCODE_DEFINE 0ECh   ; SET 5, H
lahf
or    bh, (1 SHL 5)
sahf
LOAD_NEXT_INSTRUCTION_SEGMENT_2 2

OPCODE_DEFINE 0EDh   ; SET 5, L
lahf
or    bl, (1 SHL 5)
sahf
LOAD_NEXT_INSTRUCTION_SEGMENT_2 2

OPCODE_DEFINE 0EEh   ; SET 5, (HL)
lahf
or    byte ptr ds:[bx],  (1 SHL 5)
sahf
LOAD_NEXT_INSTRUCTION_SEGMENT_2 4

OPCODE_DEFINE 0EFh   ; SET 5, A
lahf
or    cl, (1 SHL 5)
sahf
LOAD_NEXT_INSTRUCTION_SEGMENT_2 2

OPCODE_DEFINE 0F0h   ; SET 6, B
lahf
or    bp, ( (1 SHL 6) SHL 8)
sahf
LOAD_NEXT_INSTRUCTION_SEGMENT_2 2

OPCODE_DEFINE 0F1h   ; SET 6, C
lahf
or    bp, (1 SHL 6)
sahf
LOAD_NEXT_INSTRUCTION_SEGMENT_2 2

OPCODE_DEFINE 0F2h   ; SET 6, D
lahf
or    dh, (1 SHL 6)
sahf
LOAD_NEXT_INSTRUCTION_SEGMENT_2 2

OPCODE_DEFINE 0F3h   ; SET 6, E
lahf
or    dl, (1 SHL 6)
sahf
LOAD_NEXT_INSTRUCTION_SEGMENT_2 2

OPCODE_DEFINE 0F4h   ; SET 6, H
lahf
or    bh, (1 SHL 6)
sahf
LOAD_NEXT_INSTRUCTION_SEGMENT_2 2

OPCODE_DEFINE 0F5h   ; SET 6, L
lahf
or    bl, (1 SHL 6)
sahf
LOAD_NEXT_INSTRUCTION_SEGMENT_2 2

OPCODE_DEFINE 0F6h   ; SET 6, (HL)
lahf
or    byte ptr ds:[bx],  (1 SHL 6)
sahf
LOAD_NEXT_INSTRUCTION_SEGMENT_2 4

OPCODE_DEFINE 0F7h   ; SET 6, A
lahf
or    cl, (1 SHL 6)
sahf
LOAD_NEXT_INSTRUCTION_SEGMENT_2 2

OPCODE_DEFINE 0F8h   ; SET 7, B
lahf
or    bp, ( (1 SHL 7) SHL 8)
sahf
LOAD_NEXT_INSTRUCTION_SEGMENT_2 2

OPCODE_DEFINE 0F9h   ; SET 7, C
lahf
or    bp, (1 SHL 7)
sahf
LOAD_NEXT_INSTRUCTION_SEGMENT_2 2

OPCODE_DEFINE 0FAh   ; SET 7, D
lahf
or    dh, (1 SHL 7)
sahf
LOAD_NEXT_INSTRUCTION_SEGMENT_2 2

OPCODE_DEFINE 0FBh   ; SET 7, E
lahf
or    dl, (1 SHL 7)
sahf
LOAD_NEXT_INSTRUCTION_SEGMENT_2 2

OPCODE_DEFINE 0FCh   ; SET 7, H
lahf
or    bh, (1 SHL 7)
sahf
LOAD_NEXT_INSTRUCTION_SEGMENT_2 2

OPCODE_DEFINE 0FDh   ; SET 7, L
lahf
or    bl, (1 SHL 7)
sahf
LOAD_NEXT_INSTRUCTION_SEGMENT_2 2

OPCODE_DEFINE 0FEh   ; SET 7, (HL)
lahf
or    byte ptr ds:[bx],  (1 SHL 7)
sahf
LOAD_NEXT_INSTRUCTION_SEGMENT_2 4

OPCODE_DEFINE 0FFh   ; SET 7, A

COMMENT @
lahf
or    cl, (1 SHL 7)
sahf
LOAD_NEXT_INSTRUCTION_SEGMENT_2 2

@





ENDS  ; CORE2


END