.8086
.MODEL medium
INCLUDE gb_defs.inc

; CB prefix instruction handling

EXTRN CORE1_START

CORE1 SEGMENT
  ASSUME CS:CORE1
ENDS



SEGMENT CORE2  USE16 PARA PUBLIC 'CODE'
ASSUME  CS:CORE2

OPCODE_DEFINE 000h   ; RLC B

INCREMENT_CYCLES 1

CORE2_START:
public CORE2_START

LOAD_NEXT_INSTRUCTION_NOCYCLES

OPCODE_DEFINE 001h   ; RLC C
OPCODE_DEFINE 002h   ; RLC D
OPCODE_DEFINE 003h   ; RLC E
OPCODE_DEFINE 004h   ; RLC H
OPCODE_DEFINE 005h   ; RLC L
OPCODE_DEFINE 006h   ; RLC (HL)
OPCODE_DEFINE 007h   ; RLC A
OPCODE_DEFINE 008h   ; RRC B
OPCODE_DEFINE 009h   ; RRC C
OPCODE_DEFINE 00Ah   ; RRC D
OPCODE_DEFINE 00Bh   ; RRC E
OPCODE_DEFINE 00Ch   ; RRC H
OPCODE_DEFINE 00Dh   ; RRC L
OPCODE_DEFINE 00Eh   ; RRC (HL)
OPCODE_DEFINE 00Fh   ; RRC A
OPCODE_DEFINE 010h   ; RL B
OPCODE_DEFINE 011h   ; RL C
OPCODE_DEFINE 012h   ; RL D
OPCODE_DEFINE 013h   ; RL E
OPCODE_DEFINE 014h   ; RL H
OPCODE_DEFINE 015h   ; RL L
OPCODE_DEFINE 016h   ; RL (HL)
OPCODE_DEFINE 017h   ; RL A
OPCODE_DEFINE 018h   ; RR B
OPCODE_DEFINE 019h   ; RR C
OPCODE_DEFINE 01Ah   ; RR D
OPCODE_DEFINE 01Bh   ; RR E
OPCODE_DEFINE 01Ch   ; RR H
OPCODE_DEFINE 01Dh   ; RR L
OPCODE_DEFINE 01Eh   ; RR (HL)
OPCODE_DEFINE 01Fh   ; RR A
OPCODE_DEFINE 020h   ; SLA B
OPCODE_DEFINE 021h   ; SLA C
OPCODE_DEFINE 022h   ; SLA D
OPCODE_DEFINE 023h   ; SLA E
OPCODE_DEFINE 024h   ; SLA H
OPCODE_DEFINE 025h   ; SLA L
OPCODE_DEFINE 026h   ; SLA (HL)
OPCODE_DEFINE 027h   ; SLA A
OPCODE_DEFINE 028h   ; SRA B
OPCODE_DEFINE 029h   ; SRA C
OPCODE_DEFINE 02Ah   ; SRA D
OPCODE_DEFINE 02Bh   ; SRA E
OPCODE_DEFINE 02Ch   ; SRA H
OPCODE_DEFINE 02Dh   ; SRA L
OPCODE_DEFINE 02Eh   ; SRA (HL)
OPCODE_DEFINE 02Fh   ; SRA A
OPCODE_DEFINE 030h   ; SWAP B
OPCODE_DEFINE 031h   ; SWAP C
OPCODE_DEFINE 032h   ; SWAP D
OPCODE_DEFINE 033h   ; SWAP E
OPCODE_DEFINE 034h   ; SWAP H
OPCODE_DEFINE 035h   ; SWAP L
OPCODE_DEFINE 036h   ; SWAP (HL)
OPCODE_DEFINE 037h   ; SWAP A
OPCODE_DEFINE 038h   ; SRL B
OPCODE_DEFINE 039h   ; SRL C
OPCODE_DEFINE 03Ah   ; SRL D
OPCODE_DEFINE 03Bh   ; SRL E
OPCODE_DEFINE 03Ch   ; SRL H
OPCODE_DEFINE 03Dh   ; SRL L
OPCODE_DEFINE 03Eh   ; SRL (HL)
OPCODE_DEFINE 03Fh   ; SRL A
OPCODE_DEFINE 040h   ; BIT 0, B
OPCODE_DEFINE 041h   ; BIT 0, C
OPCODE_DEFINE 042h   ; BIT 0, D
OPCODE_DEFINE 043h   ; BIT 0, E
OPCODE_DEFINE 044h   ; BIT 0, H
OPCODE_DEFINE 045h   ; BIT 0, L
OPCODE_DEFINE 046h   ; BIT 0, (HL)
OPCODE_DEFINE 047h   ; BIT 0, A
OPCODE_DEFINE 048h   ; BIT 1, B
OPCODE_DEFINE 049h   ; BIT 1, C
OPCODE_DEFINE 04Ah   ; BIT 1, D
OPCODE_DEFINE 04Bh   ; BIT 1, E
OPCODE_DEFINE 04Ch   ; BIT 1, H
OPCODE_DEFINE 04Dh   ; BIT 1, L
OPCODE_DEFINE 04Eh   ; BIT 1, (HL)
OPCODE_DEFINE 04Fh   ; BIT 1, A
OPCODE_DEFINE 050h   ; BIT 2, B
OPCODE_DEFINE 051h   ; BIT 2, C
OPCODE_DEFINE 052h   ; BIT 2, D
OPCODE_DEFINE 053h   ; BIT 2, E
OPCODE_DEFINE 054h   ; BIT 2, H
OPCODE_DEFINE 055h   ; BIT 2, L
OPCODE_DEFINE 056h   ; BIT 2, (HL)
OPCODE_DEFINE 057h   ; BIT 2, A
OPCODE_DEFINE 058h   ; BIT 3, B
OPCODE_DEFINE 059h   ; BIT 3, C
OPCODE_DEFINE 05Ah   ; BIT 3, D
OPCODE_DEFINE 05Bh   ; BIT 3, E
OPCODE_DEFINE 05Ch   ; BIT 3, H
OPCODE_DEFINE 05Dh   ; BIT 3, L
OPCODE_DEFINE 05Eh   ; BIT 3, (HL)
OPCODE_DEFINE 05Fh   ; BIT 3, A
OPCODE_DEFINE 060h   ; BIT 4, B
OPCODE_DEFINE 061h   ; BIT 4, C
OPCODE_DEFINE 062h   ; BIT 4, D
OPCODE_DEFINE 063h   ; BIT 4, E
OPCODE_DEFINE 064h   ; BIT 4, H
OPCODE_DEFINE 065h   ; BIT 4, L
OPCODE_DEFINE 066h   ; BIT 4, (HL)
OPCODE_DEFINE 067h   ; BIT 4, A
OPCODE_DEFINE 068h   ; BIT 5, B
OPCODE_DEFINE 069h   ; BIT 5, C
OPCODE_DEFINE 06Ah   ; BIT 5, D
OPCODE_DEFINE 06Bh   ; BIT 5, E
OPCODE_DEFINE 06Ch   ; BIT 5, H
OPCODE_DEFINE 06Dh   ; BIT 5, L
OPCODE_DEFINE 06Eh   ; BIT 5, (HL)
OPCODE_DEFINE 06Fh   ; BIT 5, A
OPCODE_DEFINE 070h   ; BIT 6, B
OPCODE_DEFINE 071h   ; BIT 6, C
OPCODE_DEFINE 072h   ; BIT 6, D
OPCODE_DEFINE 073h   ; BIT 6, E
OPCODE_DEFINE 074h   ; BIT 6, H
OPCODE_DEFINE 075h   ; BIT 6, L
OPCODE_DEFINE 076h   ; BIT 6, (HL)
OPCODE_DEFINE 077h   ; BIT 6, A
OPCODE_DEFINE 078h   ; BIT 7, B
OPCODE_DEFINE 079h   ; BIT 7, C
OPCODE_DEFINE 07Ah   ; BIT 7, D
OPCODE_DEFINE 07Bh   ; BIT 7, E
OPCODE_DEFINE 07Ch   ; BIT 7, H
OPCODE_DEFINE 07Dh   ; BIT 7, L
OPCODE_DEFINE 07Eh   ; BIT 7, (HL)
OPCODE_DEFINE 07Fh   ; BIT 7, A
OPCODE_DEFINE 080h   ; RES 0, B
OPCODE_DEFINE 081h   ; RES 0, C
OPCODE_DEFINE 082h   ; RES 0, D
OPCODE_DEFINE 083h   ; RES 0, E
OPCODE_DEFINE 084h   ; RES 0, H
OPCODE_DEFINE 085h   ; RES 0, L
OPCODE_DEFINE 086h   ; RES 0, (HL)
OPCODE_DEFINE 087h   ; RES 0, A
OPCODE_DEFINE 088h   ; RES 1, B
OPCODE_DEFINE 089h   ; RES 1, C
OPCODE_DEFINE 08Ah   ; RES 1, D
OPCODE_DEFINE 08Bh   ; RES 1, E
OPCODE_DEFINE 08Ch   ; RES 1, H
OPCODE_DEFINE 08Dh   ; RES 1, L
OPCODE_DEFINE 08Eh   ; RES 1, (HL)
OPCODE_DEFINE 08Fh   ; RES 1, A
OPCODE_DEFINE 090h   ; RES 2, B
OPCODE_DEFINE 091h   ; RES 2, C
OPCODE_DEFINE 092h   ; RES 2, D
OPCODE_DEFINE 093h   ; RES 2, E
OPCODE_DEFINE 094h   ; RES 2, H
OPCODE_DEFINE 095h   ; RES 2, L
OPCODE_DEFINE 096h   ; RES 2, (HL)
OPCODE_DEFINE 097h   ; RES 2, A
OPCODE_DEFINE 098h   ; RES 3, B
OPCODE_DEFINE 099h   ; RES 3, C
OPCODE_DEFINE 09Ah   ; RES 3, D
OPCODE_DEFINE 09Bh   ; RES 3, E
OPCODE_DEFINE 09Ch   ; RES 3, H
OPCODE_DEFINE 09Dh   ; RES 3, L
OPCODE_DEFINE 09Eh   ; RES 3, (HL)
OPCODE_DEFINE 09Fh   ; RES 3, A
OPCODE_DEFINE 0A0h   ; RES 4, B
OPCODE_DEFINE 0A1h   ; RES 4, C
OPCODE_DEFINE 0A2h   ; RES 4, D
OPCODE_DEFINE 0A3h   ; RES 4, E
OPCODE_DEFINE 0A4h   ; RES 4, H
OPCODE_DEFINE 0A5h   ; RES 4, L
OPCODE_DEFINE 0A6h   ; RES 4, (HL)
OPCODE_DEFINE 0A7h   ; RES 4, A
OPCODE_DEFINE 0A8h   ; RES 5, B
OPCODE_DEFINE 0A9h   ; RES 5, C
OPCODE_DEFINE 0AAh   ; RES 5, D
OPCODE_DEFINE 0ABh   ; RES 5, E
OPCODE_DEFINE 0ACh   ; RES 5, H
OPCODE_DEFINE 0ADh   ; RES 5, L
OPCODE_DEFINE 0AEh   ; RES 5, (HL)
OPCODE_DEFINE 0AFh   ; RES 5, A
OPCODE_DEFINE 0B0h   ; RES 6, B
OPCODE_DEFINE 0B1h   ; RES 6, C
OPCODE_DEFINE 0B2h   ; RES 6, D
OPCODE_DEFINE 0B3h   ; RES 6, E
OPCODE_DEFINE 0B4h   ; RES 6, H
OPCODE_DEFINE 0B5h   ; RES 6, L
OPCODE_DEFINE 0B6h   ; RES 6, (HL)
OPCODE_DEFINE 0B7h   ; RES 6, A
OPCODE_DEFINE 0B8h   ; RES 7, B
OPCODE_DEFINE 0B9h   ; RES 7, C
OPCODE_DEFINE 0BAh   ; RES 7, D
OPCODE_DEFINE 0BBh   ; RES 7, E
OPCODE_DEFINE 0BCh   ; RES 7, H
OPCODE_DEFINE 0BDh   ; RES 7, L
OPCODE_DEFINE 0BEh   ; RES 7, (HL)
OPCODE_DEFINE 0BFh   ; RES 7, A
OPCODE_DEFINE 0C0h   ; SET 0, B
OPCODE_DEFINE 0C1h   ; SET 0, C
OPCODE_DEFINE 0C2h   ; SET 0, D
OPCODE_DEFINE 0C3h   ; SET 0, E
OPCODE_DEFINE 0C4h   ; SET 0, H
OPCODE_DEFINE 0C5h   ; SET 0, L
OPCODE_DEFINE 0C6h   ; SET 0, (HL)
OPCODE_DEFINE 0C7h   ; SET 0, A
OPCODE_DEFINE 0C8h   ; SET 1, B
OPCODE_DEFINE 0C9h   ; SET 1, C
OPCODE_DEFINE 0CAh   ; SET 1, D
OPCODE_DEFINE 0CBh   ; SET 1, E
OPCODE_DEFINE 0CCh   ; SET 1, H
OPCODE_DEFINE 0CDh   ; SET 1, L
OPCODE_DEFINE 0CEh   ; SET 1, (HL)
OPCODE_DEFINE 0CFh   ; SET 1, A
OPCODE_DEFINE 0D0h   ; SET 2, B
OPCODE_DEFINE 0D1h   ; SET 2, C
OPCODE_DEFINE 0D2h   ; SET 2, D
OPCODE_DEFINE 0D3h   ; SET 2, E
OPCODE_DEFINE 0D4h   ; SET 2, H
OPCODE_DEFINE 0D5h   ; SET 2, L
OPCODE_DEFINE 0D6h   ; SET 2, (HL)
OPCODE_DEFINE 0D7h   ; SET 2, A
OPCODE_DEFINE 0D8h   ; SET 3, B
OPCODE_DEFINE 0D9h   ; SET 3, C
OPCODE_DEFINE 0DAh   ; SET 3, D
OPCODE_DEFINE 0DBh   ; SET 3, E
OPCODE_DEFINE 0DCh   ; SET 3, H
OPCODE_DEFINE 0DDh   ; SET 3, L
OPCODE_DEFINE 0DEh   ; SET 3, (HL)
OPCODE_DEFINE 0DFh   ; SET 3, A
OPCODE_DEFINE 0E0h   ; SET 4, B
OPCODE_DEFINE 0E1h   ; SET 4, C
OPCODE_DEFINE 0E2h   ; SET 4, D
OPCODE_DEFINE 0E3h   ; SET 4, E
OPCODE_DEFINE 0E4h   ; SET 4, H
OPCODE_DEFINE 0E5h   ; SET 4, L
OPCODE_DEFINE 0E6h   ; SET 4, (HL)
OPCODE_DEFINE 0E7h   ; SET 4, A
OPCODE_DEFINE 0E8h   ; SET 5, B
OPCODE_DEFINE 0E9h   ; SET 5, C
OPCODE_DEFINE 0EAh   ; SET 5, D
OPCODE_DEFINE 0EBh   ; SET 5, E
OPCODE_DEFINE 0ECh   ; SET 5, H
OPCODE_DEFINE 0EDh   ; SET 5, L
OPCODE_DEFINE 0EEh   ; SET 5, (HL)
OPCODE_DEFINE 0EFh   ; SET 5, A
OPCODE_DEFINE 0F0h   ; SET 6, B
OPCODE_DEFINE 0F1h   ; SET 6, C
OPCODE_DEFINE 0F2h   ; SET 6, D
OPCODE_DEFINE 0F3h   ; SET 6, E
OPCODE_DEFINE 0F4h   ; SET 6, H
OPCODE_DEFINE 0F5h   ; SET 6, L
OPCODE_DEFINE 0F6h   ; SET 6, (HL)
OPCODE_DEFINE 0F7h   ; SET 6, A
OPCODE_DEFINE 0F8h   ; SET 7, B
OPCODE_DEFINE 0F9h   ; SET 7, C
OPCODE_DEFINE 0FAh   ; SET 7, D
OPCODE_DEFINE 0FBh   ; SET 7, E
OPCODE_DEFINE 0FCh   ; SET 7, H
OPCODE_DEFINE 0FDh   ; SET 7, L
OPCODE_DEFINE 0FEh   ; SET 7, (HL)
OPCODE_DEFINE 0FFh   ; SET 7, A






ENDS  ; CORE2


END