.8086
.MODEL medium
INCLUDE gb_defs.inc



SEGMENT CORE1  USE16 PARA PUBLIC 'CODE'
ASSUME CS:CORE1



OPCODE_DEFINE 000h   ; NOP
INCREMENT_CYCLES 1

CORE1_START:
public CORE1_START

LOAD_NEXT_INSTRUCTION


OPCODE_DEFINE 001h   ; LD BC, d16
OPCODE_DEFINE 002h   ; LD (BC), A   
OPCODE_DEFINE 003h   ; INC BC
OPCODE_DEFINE 004h   ; INC B
OPCODE_DEFINE 005h   ; DEC B
OPCODE_DEFINE 006h   ; LD B, d8
OPCODE_DEFINE 007h   ; RLCA

OPCODE_DEFINE 008h   ; LD (a16), SP

OPCODE_DEFINE 009h   ; ADD HL, BC

OPCODE_DEFINE 00Ah   ; ADD HL, BC

OPCODE_DEFINE 00Bh   ; ADD HL, BC

OPCODE_DEFINE 00Ch   ; INC C
OPCODE_DEFINE 00Dh   ; DEC C
OPCODE_DEFINE 00Eh   ; LD C, d8

OPCODE_DEFINE 00Fh   ; RRCA

OPCODE_DEFINE 010h   ; STOP
OPCODE_DEFINE 011h   ; LD DE, d16
OPCODE_DEFINE 012h   ; LD (DE), A
OPCODE_DEFINE 013h   ; INC DE
OPCODE_DEFINE 014h   ; INC D
OPCODE_DEFINE 015h   ; DEC D
OPCODE_DEFINE 016h   ; LD D, d8

OPCODE_DEFINE 017h   ; RLA
OPCODE_DEFINE 018h   ; JR s8
OPCODE_DEFINE 019h   ; ADD HL, DE

OPCODE_DEFINE 01Ah   ; LD A, (DE)

OPCODE_DEFINE 01Bh   ; DEC DE

OPCODE_DEFINE 01Ch   ; INC E
OPCODE_DEFINE 01Dh   ; DEC E
OPCODE_DEFINE 01Eh   ; LD E, d8

OPCODE_DEFINE 01Fh   ; RRA


OPCODE_DEFINE 020h   ; JR NZ, s8

OPCODE_DEFINE 021h   ; LD HL, d16

OPCODE_DEFINE 022h   ; LD (HL+), A

OPCODE_DEFINE 023h   ; INC HL
OPCODE_DEFINE 024h   ; INC H
OPCODE_DEFINE 025h   ; DEC H
OPCODE_DEFINE 026h   ; LD H, d8

OPCODE_DEFINE 027h   ; DAA

OPCODE_DEFINE 028h   ; JR Z, s8

OPCODE_DEFINE 029h   ; ADD HL, HL

OPCODE_DEFINE 02Ah   ; LD A, (HL+)

OPCODE_DEFINE 02Bh   ; DEC HL

OPCODE_DEFINE 02Ch   ; INC L
OPCODE_DEFINE 02Dh   ; DEC L
OPCODE_DEFINE 02Eh   ; LD L, d8

OPCODE_DEFINE 02Fh   ; CPL

OPCODE_DEFINE 030h   ; JR NC, s8

OPCODE_DEFINE 031h   ; LD SP, d16

OPCODE_DEFINE 032h   ; LD (HL-), A

OPCODE_DEFINE 033h   ; INC SP
OPCODE_DEFINE 034h   ; INC (HL)
OPCODE_DEFINE 035h   ; DEC (HL)
OPCODE_DEFINE 036h   ; LD (HL), d8

OPCODE_DEFINE 037h   ; SCF
OPCODE_DEFINE 038h   ; JR C, s8

OPCODE_DEFINE 039h   ; ADD HL, SP

OPCODE_DEFINE 03Ah   ; LD A, (HL-)

OPCODE_DEFINE 03Bh   ; DEC SP
OPCODE_DEFINE 03Ch   ; INC A
OPCODE_DEFINE 03Dh   ; DEC A
OPCODE_DEFINE 03Eh   ; LD A, d8

OPCODE_DEFINE 03Fh   ; CCF

OPCODE_DEFINE 040h   ; LD B, B
OPCODE_DEFINE 041h   ; LD B, C
OPCODE_DEFINE 042h   ; LD B, D
OPCODE_DEFINE 043h   ; LD B, E
OPCODE_DEFINE 044h   ; LD B, H
OPCODE_DEFINE 045h   ; LD B, L
OPCODE_DEFINE 046h   ; LD B, (HL)
OPCODE_DEFINE 047h   ; LD B, A
OPCODE_DEFINE 048h   ; LD C, B
OPCODE_DEFINE 049h   ; LD C, C
OPCODE_DEFINE 04Ah   ; LD C, D
OPCODE_DEFINE 04Bh   ; LD C, E
OPCODE_DEFINE 04Ch   ; LD C, H
OPCODE_DEFINE 04Dh   ; LD C, L
OPCODE_DEFINE 04Eh   ; LD C, (HL)
OPCODE_DEFINE 04Fh   ; LD C, A

OPCODE_DEFINE 050h   ; LD D, B
OPCODE_DEFINE 051h   ; LD D, C
OPCODE_DEFINE 052h   ; LD D, D
OPCODE_DEFINE 053h   ; LD D, E
OPCODE_DEFINE 054h   ; LD D, H
OPCODE_DEFINE 055h   ; LD D, L
OPCODE_DEFINE 056h   ; LD D, (HL)
OPCODE_DEFINE 057h   ; LD D, A
OPCODE_DEFINE 058h   ; LD E, B
OPCODE_DEFINE 059h   ; LD E, C
OPCODE_DEFINE 05Ah   ; LD E, D
OPCODE_DEFINE 05Bh   ; LD E, E
OPCODE_DEFINE 05Ch   ; LD E, H
OPCODE_DEFINE 05Dh   ; LD E, L
OPCODE_DEFINE 05Eh   ; LD E, (HL)
OPCODE_DEFINE 05Fh   ; LD E, A

OPCODE_DEFINE 060h   ; LD H, B
OPCODE_DEFINE 061h   ; LD H, C
OPCODE_DEFINE 062h   ; LD H, D
OPCODE_DEFINE 063h   ; LD H, E
OPCODE_DEFINE 064h   ; LD H, H
OPCODE_DEFINE 065h   ; LD H, L
OPCODE_DEFINE 066h   ; LD H, (HL)
OPCODE_DEFINE 067h   ; LD H, A
OPCODE_DEFINE 068h   ; LD L, B
OPCODE_DEFINE 069h   ; LD L, C
OPCODE_DEFINE 06Ah   ; LD L, D
OPCODE_DEFINE 06Bh   ; LD L, E
OPCODE_DEFINE 06Ch   ; LD L, H
OPCODE_DEFINE 06Dh   ; LD L, L
OPCODE_DEFINE 06Eh   ; LD L, (HL)
OPCODE_DEFINE 06Fh   ; LD L, A

OPCODE_DEFINE 070h   ; LD (HL)), B
OPCODE_DEFINE 071h   ; LD (HL)), C
OPCODE_DEFINE 072h   ; LD (HL)), D
OPCODE_DEFINE 073h   ; LD (HL)), E
OPCODE_DEFINE 074h   ; LD (HL)), H
OPCODE_DEFINE 075h   ; LD (HL)), L
OPCODE_DEFINE 076h   ; HALT
OPCODE_DEFINE 077h   ; LD (HL)), A
OPCODE_DEFINE 078h   ; LD A, B
OPCODE_DEFINE 079h   ; LD A, C
OPCODE_DEFINE 07Ah   ; LD A, D
OPCODE_DEFINE 07Bh   ; LD A, E
OPCODE_DEFINE 07Ch   ; LD A, H
OPCODE_DEFINE 07Dh   ; LD A, L
OPCODE_DEFINE 07Eh   ; LD A, (HL)
OPCODE_DEFINE 07Fh   ; LD A, A

OPCODE_DEFINE 080h   ; ADD A, B
OPCODE_DEFINE 081h   ; ADD A, C
OPCODE_DEFINE 082h   ; ADD A, D
OPCODE_DEFINE 083h   ; ADD A, E
OPCODE_DEFINE 084h   ; ADD A, H
OPCODE_DEFINE 085h   ; ADD A, L
OPCODE_DEFINE 086h   ; ADD A, (HL)
OPCODE_DEFINE 087h   ; ADD A, A
OPCODE_DEFINE 088h   ; ADC A, B
OPCODE_DEFINE 089h   ; ADC A, C
OPCODE_DEFINE 08Ah   ; ADC A, D
OPCODE_DEFINE 08Bh   ; ADC A, E
OPCODE_DEFINE 08Ch   ; ADC A, H
OPCODE_DEFINE 08Dh   ; ADC A, L
OPCODE_DEFINE 08Eh   ; ADD AC (HL)
OPCODE_DEFINE 08Fh   ; ADC A, A

OPCODE_DEFINE 090h   ; SUB B
OPCODE_DEFINE 091h   ; SUB C
OPCODE_DEFINE 092h   ; SUB D
OPCODE_DEFINE 093h   ; SUB E
OPCODE_DEFINE 094h   ; SUB H
OPCODE_DEFINE 095h   ; SUB L
OPCODE_DEFINE 096h   ; SUB (HL)
OPCODE_DEFINE 097h   ; SUB A
OPCODE_DEFINE 098h   ; SBC B
OPCODE_DEFINE 099h   ; SBC C
OPCODE_DEFINE 09Ah   ; SBC D
OPCODE_DEFINE 09Bh   ; SBC E
OPCODE_DEFINE 09Ch   ; SBC H
OPCODE_DEFINE 09Dh   ; SBC L
OPCODE_DEFINE 09Eh   ; SBC (HL)
OPCODE_DEFINE 09Fh   ; SBC A

OPCODE_DEFINE 0A0h   ; AND B
OPCODE_DEFINE 0A1h   ; AND C
OPCODE_DEFINE 0A2h   ; AND D
OPCODE_DEFINE 0A3h   ; AND E
OPCODE_DEFINE 0A4h   ; AND H
OPCODE_DEFINE 0A5h   ; AND L
OPCODE_DEFINE 0A6h   ; AND (HL)
OPCODE_DEFINE 0A7h   ; AND A
OPCODE_DEFINE 0A8h   ; XOR B
OPCODE_DEFINE 0A9h   ; XOR C
OPCODE_DEFINE 0AAh   ; XOR D
OPCODE_DEFINE 0ABh   ; XOR E
OPCODE_DEFINE 0ACh   ; XOR H
OPCODE_DEFINE 0ADh   ; XOR L
OPCODE_DEFINE 0AEh   ; XOR (HL)
OPCODE_DEFINE 0AFh   ; XOR A

OPCODE_DEFINE 0B0h   ; OR B
OPCODE_DEFINE 0B1h   ; OR C
OPCODE_DEFINE 0B2h   ; OR D
OPCODE_DEFINE 0B3h   ; OR E
OPCODE_DEFINE 0B4h   ; OR H
OPCODE_DEFINE 0B5h   ; OR L
OPCODE_DEFINE 0B6h   ; OR (HL)
OPCODE_DEFINE 0B7h   ; OR A
OPCODE_DEFINE 0B8h   ; CP B
OPCODE_DEFINE 0B9h   ; CP C
OPCODE_DEFINE 0BAh   ; CP D
OPCODE_DEFINE 0BBh   ; CP E
OPCODE_DEFINE 0BCh   ; CP H
OPCODE_DEFINE 0BDh   ; CP L
OPCODE_DEFINE 0BEh   ; CP (HL)
OPCODE_DEFINE 0BFh   ; CP A

OPCODE_DEFINE 0C0h   ; RET NZ
OPCODE_DEFINE 0C1h   ; POP BC
OPCODE_DEFINE 0C2h   ; JP NZ, a16
OPCODE_DEFINE 0C3h   ; JP a16
OPCODE_DEFINE 0C4h   ; CALL NZ, a16
OPCODE_DEFINE 0C5h   ; PUSH BC
OPCODE_DEFINE 0C6h   ; ADD A, d8
OPCODE_DEFINE 0C7h   ; RST 0
OPCODE_DEFINE 0C8h   ; RET Z
OPCODE_DEFINE 0C9h   ; RET
OPCODE_DEFINE 0CAh   ; JP Z, a16
OPCODE_DEFINE 0CBh   ; FIRST BYTE OF TWO BYTE CALL

; jump into core 2 

mov  ax, 3

pointer_to_core_2:
public pointer_to_core_2
dw 0000, 0000   ; TODO selfmodify

OPCODE_DEFINE 0CCh   ; CALL Z, a16
OPCODE_DEFINE 0CDh   ; CALL a16
OPCODE_DEFINE 0CEh   ; ADC A, d8
OPCODE_DEFINE 0CFh   ; RST 1

OPCODE_DEFINE 0D0h   ; RET NC
OPCODE_DEFINE 0D1h   ; POP DE
OPCODE_DEFINE 0D2h   ; JP NC, a16
OPCODE_DEFINE 0D3h   ; xxxx
OPCODE_DEFINE 0D4h   ; CALL NC, a16
OPCODE_DEFINE 0D5h   ; PUSH DE
OPCODE_DEFINE 0D6h   ; SUB d8
OPCODE_DEFINE 0D7h   ; RST 2
OPCODE_DEFINE 0D8h   ; RET C
OPCODE_DEFINE 0D9h   ; RETI
OPCODE_DEFINE 0DAh   ; JP C, a16
OPCODE_DEFINE 0DBh   ; xxxx
OPCODE_DEFINE 0DCh   ; CALL C, a16
OPCODE_DEFINE 0DDh   ; xxxx
OPCODE_DEFINE 0DEh   ; SBC A, d8
OPCODE_DEFINE 0DFh   ; RST 3

OPCODE_DEFINE 0E0h   ; LD (a8), A
OPCODE_DEFINE 0E1h   ; POP HL
OPCODE_DEFINE 0E2h   ; LD (C), A
OPCODE_DEFINE 0E3h   ; xxxx
OPCODE_DEFINE 0E4h   ; xxxx
OPCODE_DEFINE 0E5h   ; PUSH HL
OPCODE_DEFINE 0E6h   ; AND d8
OPCODE_DEFINE 0E7h   ; RST 4
OPCODE_DEFINE 0E8h   ; ADD SP, s8
OPCODE_DEFINE 0E9h   ; JP HL
OPCODE_DEFINE 0EAh   ; LD (a16), A
OPCODE_DEFINE 0EBh   ; xxxx
OPCODE_DEFINE 0ECh   ; xxxx
OPCODE_DEFINE 0EDh   ; xxxx
OPCODE_DEFINE 0EEh   ; XOR d8
OPCODE_DEFINE 0EFh   ; RST 5

OPCODE_DEFINE 0F0h   ; LD A, (a8)
OPCODE_DEFINE 0F1h   ; POP AF
OPCODE_DEFINE 0F2h   ; LD A, (C)
OPCODE_DEFINE 0F3h   ; DI
OPCODE_DEFINE 0F4h   ; xxxx
OPCODE_DEFINE 0F5h   ; PUSH AF
OPCODE_DEFINE 0F6h   ; OR d8
OPCODE_DEFINE 0F7h   ; RST 6
OPCODE_DEFINE 0F8h   ; LD HL, SP+s8
OPCODE_DEFINE 0F9h   ; LD SP, HL
OPCODE_DEFINE 0FAh   ; LD A, (a16)
OPCODE_DEFINE 0FBh   ; EI
OPCODE_DEFINE 0FCh   ; xxxx
OPCODE_DEFINE 0FDh   ; xxxx
OPCODE_DEFINE 0FEh   ; CP d8
OPCODE_DEFINE 0FFh   ; RST 7






ENDS  ; CORE1


END